#!/bin/sh

echo "Choosing random wallpaper..."
wall=$(find $HOME/pix/wall -type f | shuf -n 1)
echo "Setting up wallpaper..."
echo "Generating pywal color schemes..."
wal -i $wall >dev/null
sed -i 'N;$!P;D' $HOME/.cache/colors-wal-dwm.h
echo "Recompiling dwm with new colors..."
(cd $HOME/.config/dwm && sudo make clean install>/dev/null)

echo "Restart dwm fo new look"
